add_newline = false
command_timeout = 2000

[battery]
full_symbol = "• "
charging_symbol = "⇡ "
discharging_symbol = "⇣ "
unknown_symbol = "❓ "
empty_symbol = "❗ "


[character] 
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
